Map<String, Map<String, dynamic>> currencies = {
  "NZD": {"cur_name": "Новозеландский доллар", "img_name": "nz.png", "cur_symbol": "\$", "cur_code": "NZD", "allowable_cur_list": ['RUB']},
  "LKR": {"cur_name": "Шри-ланкийская рупия", "img_name": "lk.png", "cur_symbol": "ரூ", "cur_code": "LKR", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "AED": {"cur_name": "Дирхам ОАЭ", "img_name": "ae.png", "cur_symbol": "Dh", "cur_code": "AED", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "GBP": {"cur_name": "Британский фунт стерлингов", "img_name": "gb.png", "cur_symbol": "£", "cur_code": "GBP", "allowable_cur_list": ['BCH', 'BTC', 'ETH', 'EUR', 'AUD', 'BYN', 'JPY', 'RUB', 'USD', 'XRP']},
  "AUD": {"cur_name": "Австралийский доллар", "img_name": "au.png", "cur_symbol": "\$", "cur_code": "AUD", "allowable_cur_list": ['GBP', 'RUB', 'USD']},
  "CAD": {"cur_name": "Канадский доллар", "img_name": "ca.png", "cur_symbol": "C\$", "cur_code": "CAD", "allowable_cur_list": ['RUB', 'USD']},
  "SGD": {"cur_name": "Сингапурский доллар", "img_name": "sg.png", "cur_symbol": "S\$", "cur_code": "SGD", "allowable_cur_list": ['RUB']},
  "GEL": {"cur_name": "Грузинский лари", "img_name": "ge.png", "cur_symbol": "ლ", "cur_code": "GEL", "allowable_cur_list": ['RUB', 'USD']},
  "EUR": {"cur_name": "Евро", "img_name": "eu.png", "cur_symbol": "€", "cur_code": "EUR", "allowable_cur_list": ['BCH', 'BTC', 'CNY', 'ETH', 'AED', 'AMD', 'BGN', 'BYN', 'GBP', 'JPY', 'KZT', 'RUB', 'TRY', 'USD', 'LKR', 'MDL', 'MMK', 'RSD', 'THB', 'XRP']},
  "RUB": {"cur_name": "Российский рубль", "img_name": "ru.png", "cur_symbol": "руб", "cur_code": "RUB", "allowable_cur_list": ['BCH', 'BTC', 'BYN', 'CAD', 'CHF', 'CNY', 'ETH', 'EUR', 'GBP', 'GEL', 'JPY', 'LKR', 'MDL', 'MMK', 'RSD', 'AED', 'AMD', 'AUD', 'BGN', 'KZT', 'MYR', 'NZD', 'SGD', 'TRY', 'UAH', 'THB', 'USD', 'XRP']},
  "ILS": {"cur_name": "Новый израильский шекель", "img_name": "il.png", "cur_symbol": "₪", "cur_code": "ILS", "allowable_cur_list": ['USD']},
  "BYN": {"cur_name": "Белорусский рубль", "img_name": "by.png", "cur_symbol": "Br", "cur_code": "BYN", "allowable_cur_list": ['RUB', 'EUR', 'GBP', 'USD']},
  "MYR": {"cur_name": "Малайзийский ринггит", "img_name": "my.png", "cur_symbol": "RM", "cur_code": "MYR", "allowable_cur_list": ['RUB', 'USD']},
  "AMD": {"cur_name": "Армянский драм", "img_name": "am.png", "cur_symbol": "AMD", "cur_code": "AMD", "allowable_cur_list": ['EUR', 'JPY', 'RUB', 'USD']},
  "USD": {"cur_name": "Доллар США", "img_name": "us.png", "cur_symbol": "\$", "cur_code": "USD", "allowable_cur_list": ['BCH', 'BTC', 'BTG', 'CNY', 'ETH', 'EUR', 'GEL', 'IDR', 'LKR', 'MDL', 'MMK', 'RSD', 'AED', 'AMD', 'AUD', 'BGN', 'BYN', 'CAD', 'GBP', 'ILS', 'JPY', 'KGS', 'KZT', 'MYR', 'RUB', 'THB', 'UAH', 'VND', 'XRP', 'ZEC']},
  "RSD": {"cur_name": "Сербский динар", "img_name": "rs.png", "cur_symbol": "RSD", "cur_code": "RSD", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "VND": {"cur_name": "Вьетнамский донг", "img_name": "vn.png", "cur_symbol": "₫", "cur_code": "VND", "allowable_cur_list": ['USD']},
  "MMK": {"cur_name": "Мьянманский кьят", "img_name": "mm.png", "cur_symbol": "K", "cur_code": "MMK", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "AZN": {"cur_name": "Азербайджанский манат", "img_name": "az.png", "cur_symbol": "M", "cur_code": "AZN", "allowable_cur_list": ['JPY']},
  "JPY": {"cur_name": "Японская иена", "img_name": "jp.png", "cur_symbol": "¥", "cur_code": "JPY", "allowable_cur_list": ['BCH', 'BTC', 'ETH', 'EUR', 'GBP', 'AMD', 'AZN', 'RUB', 'USD', 'XRP']},
  "BGN": {"cur_name": "Болгарский лев", "img_name": "bg.png", "cur_symbol": "лв", "cur_code": "BGN", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "THB": {"cur_name": "Таиландский бат", "img_name": "th.png", "cur_symbol": "฿", "cur_code": "THB", "allowable_cur_list": ['CNY', 'EUR', 'RUB', 'USD']},
  "UAH": {"cur_name": "Украинская гривна", "img_name": "ua.png", "cur_symbol": "₴", "cur_code": "UAH", "allowable_cur_list": ['RUB', 'USD']},
  "KZT": {"cur_name": "Казахский тенге", "img_name": "kz.png", "cur_symbol": "KZT", "cur_code": "KZT", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "CHF": {"cur_name": "Швейцарский франк", "img_name": "ch.png", "cur_symbol": "₣", "cur_code": "CHF", "allowable_cur_list": ['RUB']},
  "TRY": {"cur_name": "Турецкая лира", "img_name": "tr.png", "cur_symbol": "YTL", "cur_code": "TRY", "allowable_cur_list": ['EUR', 'RUB']},
  "KGS": {"cur_name": "Киргизский сом", "img_name": "kg.png", "cur_symbol": "сом", "cur_code": "KGS", "allowable_cur_list": ['USD']},
  "CNY": {"cur_name": "Китайский юань", "img_name": "cn.png", "cur_symbol": "¥", "cur_code": "CNY", "allowable_cur_list": ['EUR', 'RUB', 'USD', 'THB']},
  "MDL": {"cur_name": "Молдавский лей", "img_name": "md.png", "cur_symbol": "MDL", "cur_code": "MDL", "allowable_cur_list": ['EUR', 'RUB', 'USD']},
  "IDR": {"cur_name": "Индонезийская рупия", "img_name": "id.png", "cur_symbol": "Rp", "cur_code": "IDR", "allowable_cur_list": ['USD']},
};



