Map<String, Map<String, String>> currencies = {
  "AFN": {"cur_name": "Афгани", "img_name": "af.png", "cur_symbol": "؋", "cur_code": "AFN"},
  "KHR": {"cur_name": "Камбоджийский риель", "img_name": "kh.png", "cur_symbol": "៛", "cur_code": "KHR"},
  "AUD": {"cur_name": "Австралийский доллар", "img_name": "au.png", "cur_symbol": "\$", "cur_code": "AUD"},
  "CUP": {"cur_name": "Кубинское песо", "img_name": "cu.png", "cur_symbol": "\$", "cur_code": "CUP"},
  "GEL": {"cur_name": "Грузинский лари", "img_name": "ge.png", "cur_symbol": "ლ", "cur_code": "GEL"},
  "HTG": {"cur_name": "Гаитянский гурд", "img_name": "ht.png", "cur_symbol": "G", "cur_code": "HTG"},
  "ILS": {"cur_name": "Новый израильский шекель", "img_name": "il.png", "cur_symbol": "₪", "cur_code": "ILS"},
  "KZT": {"cur_name": "Казахский тенге", "img_name": "kz.png", "cur_symbol": "", "cur_code": "KZT"},
  "LSL": {"cur_name": "Лоти", "img_name": "ls.png", "cur_symbol": "M", "cur_code": "LSL"},
  "MUR": {"cur_name": "Маврикийская рупия", "img_name": "mu.png", "cur_symbol": "₨", "cur_code": "MUR"},
  "MNT": {"cur_name": "Монгольский тугрик", "img_name": "mn.png", "cur_symbol": "₮", "cur_code": "MNT"},
  "MMK": {"cur_name": "Мьянманский кьят", "img_name": "mm.png", "cur_symbol": "K", "cur_code": "MMK"},
  "TZS": {"cur_name": "Танзанийский шиллинг", "img_name": "tz.png", "cur_symbol": "x", "cur_code": "TZS"},
  "RSD": {"cur_name": "Сербский динар", "img_name": "rs.png", "cur_symbol": "", "cur_code": "RSD"},
  "UZS": {"cur_name": "Узбекский сум", "img_name": "uz.png", "cur_symbol": "", "cur_code": "UZS"},
  "YER": {"cur_name": "Йеменский риал", "img_name": "ye.png", "cur_symbol": "", "cur_code": "YER"},
  "PGK": {"cur_name": "Кина Папуа – Новой Гвинеи", "img_name": "pg.png", "cur_symbol": "K", "cur_code": "PGK"},
  "UAH": {"cur_name": "Украинская гривна", "img_name": "ua.png", "cur_symbol": "₴", "cur_code": "UAH"},
  "ARS": {"cur_name": "Аргентинское песо", "img_name": "ar.png", "cur_symbol": "\$", "cur_code": "ARS"},
  "AZN": {"cur_name": "Азербайджанский манат", "img_name": "az.png", "cur_symbol": "M", "cur_code": "AZN"},
  "CNY": {"cur_name": "Китайский юань", "img_name": "cn.png", "cur_symbol": "¥", "cur_code": "CNY"},
  "CRC": {"cur_name": "Костариканский колон", "img_name": "cr.png", "cur_symbol": "₡", "cur_code": "CRC"},
  "GHS": {"cur_name": "Ганский седи", "img_name": "gh.png", "cur_symbol": "", "cur_code": "GHS"},
  "GNF": {"cur_name": "Гвинейский франк", "img_name": "gn.png", "cur_symbol": "₣", "cur_code": "GNF"},
  "JMD": {"cur_name": "Ямайский доллар", "img_name": "jm.png", "cur_symbol": "\$", "cur_code": "JMD"},
  "LAK": {"cur_name": "Лаосский кип", "img_name": "la.png", "cur_symbol": "₭", "cur_code": "LAK"},
  "MKD": {"cur_name": "Македонский денар", "img_name": "mk.png", "cur_symbol": "", "cur_code": "MKD"},
  "SDG": {"cur_name": "Суданский фунт", "img_name": "sd.png", "cur_symbol": "", "cur_code": "SDG"},
  "GBP": {"cur_name": "Британский фунт стерлингов", "img_name": "gb.png", "cur_symbol": "£", "cur_code": "GBP"},
  "AMD": {"cur_name": "Армянский драм", "img_name": "am.png", "cur_symbol": "", "cur_code": "AMD"},
  "BSD": {"cur_name": "Багамский доллар", "img_name": "bs.png", "cur_symbol": "\$", "cur_code": "BSD"},
  "KYD": {"cur_name": "Доллар Каймановых островов", "img_name": "ky.png", "cur_symbol": "\$", "cur_code": "KYD"},
  "GIP": {"cur_name": "Гибралтарский фунт", "img_name": "gi.png", "cur_symbol": "£", "cur_code": "GIP"},
  "COP": {"cur_name": "Колумбийское песо", "img_name": "co.png", "cur_symbol": "\$", "cur_code": "COP"},
  "JPY": {"cur_name": "Японская иена", "img_name": "jp.png", "cur_symbol": "¥", "cur_code": "JPY"},
  "KPW": {"cur_name": "Северокорейская вона", "img_name": "kp.png", "cur_symbol": "", "cur_code": "KPW"},
  "MDL": {"cur_name": "Молдавский лей", "img_name": "md.png", "cur_symbol": "", "cur_code": "MDL"},
  "NPR": {"cur_name": "Непальская рупия", "img_name": "np.png", "cur_symbol": "₨", "cur_code": "NPR"},
  "PHP": {"cur_name": "Филиппинское песо", "img_name": "ph.png", "cur_symbol": "₱", "cur_code": "PHP"},
  "RON": {"cur_name": "Румынский лей", "img_name": "ro.png", "cur_symbol": "L", "cur_code": "RON"},
  "ZAR": {"cur_name": "Южноафриканский рэнд", "img_name": "za.png", "cur_symbol": "R", "cur_code": "ZAR"},
  "SRD": {"cur_name": "Суринамский доллар", "img_name": "sr.png", "cur_symbol": "\$", "cur_code": "SRD"},
  "TOP": {"cur_name": "Тонганская паанга", "img_name": "to.png", "cur_symbol": "", "cur_code": "TOP"},
  "VND": {"cur_name": "Вьетнамский донг", "img_name": "vn.png", "cur_symbol": "₫", "cur_code": "VND"},
  "BBD": {"cur_name": "Барбадосский доллар", "img_name": "bb.png", "cur_symbol": "\$", "cur_code": "BBD"},
  "ALL": {"cur_name": "Албанский лек", "img_name": "al.png", "cur_symbol": "L", "cur_code": "ALL"},
  "CLP": {"cur_name": "Чилийское песо", "img_name": "cl.png", "cur_symbol": "\$", "cur_code": "CLP"},
  "CDF": {"cur_name": "Конголезский франк", "img_name": "cd.png", "cur_symbol": "", "cur_code": "CDF"},
  "HNL": {"cur_name": "Гондурасская лемпира", "img_name": "hn.png", "cur_symbol": "L", "cur_code": "HNL"},
  "GTQ": {"cur_name": "Гватемальский кетсаль", "img_name": "gt.png", "cur_symbol": "Q", "cur_code": "GTQ"},
  "MXN": {"cur_name": "Мексиканское песо", "img_name": "mx.png", "cur_symbol": "\$", "cur_code": "MXN"},
  "LRD": {"cur_name": "Либерийский доллар", "img_name": "lr.png", "cur_symbol": "\$", "cur_code": "LRD"},
  "MOP": {"cur_name": "Патака Макао", "img_name": "mo.png", "cur_symbol": "¥", "cur_code": "MOP"},
  "NZD": {"cur_name": "Новозеландский доллар", "img_name": "nz.png", "cur_symbol": "\$", "cur_code": "NZD"},
  "SHP": {"cur_name": "Фунт острова Святой Елены", "img_name": "sh.png", "cur_symbol": "", "cur_code": "SHP"},
  "PYG": {"cur_name": "Парагвайский гуарани", "img_name": "py.png", "cur_symbol": "₲", "cur_code": "PYG"},
  "SBD": {"cur_name": "Доллар Соломоновых Островов", "img_name": "sb.png", "cur_symbol": "\$", "cur_code": "SBD"},
  "CHF": {"cur_name": "Швейцарский франк", "img_name": "ch.png", "cur_symbol": "₣", "cur_code": "CHF"},
  "THB": {"cur_name": "Таиландский бат", "img_name": "th.png", "cur_symbol": "฿", "cur_code": "THB"},
  "ZMK": {"cur_name": "Квача (замбийская) (1968–2012)", "img_name": "zm.png", "cur_symbol": "", "cur_code": "ZMK"},
  "AWG": {"cur_name": "Арубанский флорин", "img_name": "aw.png", "cur_symbol": "ƒ", "cur_code": "AWG"},
  "BZD": {"cur_name": "Белизский доллар", "img_name": "bz.png", "cur_symbol": "\$", "cur_code": "BZD"},
  "BWP": {"cur_name": "Ботсванская пула", "img_name": "bw.png", "cur_symbol": "P", "cur_code": "BWP"},
  "BIF": {"cur_name": "Бурундийский франк", "img_name": "bi.png", "cur_symbol": "₣", "cur_code": "BIF"},
  "KMF": {"cur_name": "Франк Коморских Островов", "img_name": "km.png", "cur_symbol": "₣", "cur_code": "KMF"},
  "DJF": {"cur_name": "Франк Джибути", "img_name": "dj.png", "cur_symbol": "", "cur_code": "DJF"},
  "USD": {"cur_name": "Доллар США", "img_name": "us.png", "cur_symbol": "\$", "cur_code": "USD"},
  "GMD": {"cur_name": "Гамбийский даласи", "img_name": "gm.png", "cur_symbol": "", "cur_code": "GMD"},
  "GYD": {"cur_name": "Гайанский доллар", "img_name": "gy.png", "cur_symbol": "\$", "cur_code": "GYD"},
  "KRW": {"cur_name": "Южнокорейская вона", "img_name": "kr.png", "cur_symbol": "₩", "cur_code": "KRW"},
  "JOD": {"cur_name": "Иорданский динар", "img_name": "jo.png", "cur_symbol": "", "cur_code": "JOD"},
  "NGN": {"cur_name": "Нигерийская найра", "img_name": "ng.png", "cur_symbol": "₦", "cur_code": "NGN"},
  "MRO": {"cur_name": "Мавританская угия", "img_name": "mr.png", "cur_symbol": "", "cur_code": "MRO"},
  "TJS": {"cur_name": "Таджикский сомони", "img_name": "tj.png", "cur_symbol": "", "cur_code": "TJS"},
  "UYU": {"cur_name": "Уругвайское песо", "img_name": "uy.png", "cur_symbol": "", "cur_code": "UYU"},
  "SZL": {"cur_name": "Свазилендский лилангени", "img_name": "sz.png", "cur_symbol": "", "cur_code": "SZL"},
  "TTD": {"cur_name": "Доллар Тринидада и Тобаго", "img_name": "tt.png", "cur_symbol": "", "cur_code": "TTD"},
  "EUR": {"cur_name": "Евро", "img_name": "eu.png", "cur_symbol": "€", "cur_code": "EUR"},
  "RUB": {"cur_name": "Российский рубль", "img_name": "ru.png", "cur_symbol": "₽", "cur_code": "RUB"},
};



